### ISSUE TITLE
Tab completion

### ISSUE THREAD

**Issue by Boris-Ockham** [swaroopch/byte-of-python#37]
It took me a long time before I read somewhere that in at least IPython/Jupyter Notebooks (including those on https://wakari.io), IDLE and Spyder tab completion can be used. Meaning that if you start a statement and then press the tab-key a list pops up from which you can choose a completion of your statement. Coming from Microsoft Visual Studio and RStudio where the lists pop up automatically, I didn't expect something like that. I just thought that Python environments didn't work that well, and Notebooks the least of all, because typing a dot doesn't result in a list.

Tab completion is very helpful for beginners (and experts alike I suppose) so I think it would help if this would be clearly mentioned in the book.

**Comment by swaroopch** [comment]
@Boris-Ockham Thank you for your feedback. I understand your point of view and I agree that tab completion can be very helpful.

I am not sure about specifically mentioning in the book because:

1. This book is targeted for beginners, so lesser the concepts, the better. Tab completion is not necessary for a beginner to learn, and in a decade of readers, this is the first time this concept has come up.
2. I recommend PyCharm (educational edition) in the book, so if a reader uses that, they will get tab completion by default.
3. Covering all environments are out of scope for this book.

Thanks for putting time and thought into this!
