### ISSUE TITLE
Mobi layout (Kindle)

### ISSUE THREAD

**Issue by sogen** [swaroopch/byte-of-python#45]
Hi, in a Kindle paperwhite the layout appears with too many tabs, sometimes the text starts at the next line, attached screenshot:

![screen shot 2016-08-31 at 4 42 33 pm](https://cloud.githubusercontent.com/assets/2784323/18147368/f2a9009a-6f99-11e6-9dbe-b302285a5863.png)

Note: this is the .mobi file downloaded at the website: http://python.swaroopch.com

What tools are there to convert? Calibre can?

**Comment by swaroopch** [comment]
The creation of the mobi is via the gitbook software and calibre:

- https://github.com/swaroopch/byte-of-python/blob/master/INSTALL.md
- http://toolchain.gitbook.com/ebook.html

Since I'm relying on gitbook.com to generate the mobi file, I'm not sure how to fix this. Can you try generating the mobi locally and see if that renders better?
