### ISSUE TITLE
Page 9 - Portable section is chopped off at bottom

### ISSUE THREAD

**Issue by hcc-donder** [swaroopch/byte-of-python#82]
At the bottom of page 9, the Portable section is chopped off by the bottom matter.

**Comment by swaroopch** [comment]
@hcc-donder Thanks for bringing this to my notice. Unfortunately, because the [open source gitbook cli has been deprecated](https://github.com/swaroopch/byte-of-python/issues/80#issuecomment-574392526), I don't think this will ever get fixed.

The long-term solution is to migrate to something like https://pandoc.org/

**Comment by swaroopch** [comment]
After [migration from gitbook to honkit](https://github.com/swaroopch/byte-of-python/commit/9be9a7a88a88cf29adbf3364ccbe24d1cbd543c6), this seems to be resolved (after visually inspecting the mentioned section in the newly generated PDF). Please reopen if that is not true.
